<a href="https://colab.research.google.com/github/Ar8k/Assigment-2.2-CSS-Text-Styling/blob/main/Week2_Assignment_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.

In [5]:
array = np.array([1,2,3,4,5,6]) #making the array

new_array = array.reshape(2,3) # defining the new array and reshaping the old one
print(new_array)

[[1 2 3]
 [4 5 6]]


Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix

In [9]:
array_3x3 = np.array ([[1,2,3],[4,5,6],[7,8,9]]) #defining the matrix (second dim array)
array_3x2 = np.array ([[1,2],[3,4],[5,6]])
result = array_3x3@array_3x2 #multiplying the 2 matrix's
print (result)

[[ 22  28]
 [ 49  64]
 [ 76 100]]


Write a NumPy program to find the most frequent value and the number of times it occured in the array


[

    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]  
 ]

In [6]:
array1 = np.array ([
[1, 2, 3, 2, 1],
[4, 2, 5, 2, 6],
[2, 1, 2, 3, 2],
[7, 2, 8, 2, 9] ])

unique, counts =np.unique(array1, return_counts=True) #finding the unique numbers and their counts
max_numb = np.argmax(counts) #get the numb with the most shown
most_shown_numb = unique[max_numb]
times_shown = counts[max_numb]

print(f"The most shown number is: {most_shown_numb} and it was shown {times_shown} times")


The most shown number is: 2 and it was shown 9 times


Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.

[  [ 1.  2. nan  4.  5.],

 [ 6. nan  8.  9. 10.],

 [11. 12. 13. nan 15.],

 [16. 17. nan 19. 20.],

 [nan 22. 23. 24. 25.]  ]

In [12]:
data_set = np.array ([
[ 1., 2., np.nan, 4., 5.],

[ 6., np.nan, 8., 9., 10.],

[11., 12., 13., np.nan, 15.],

[16., 17., np.nan, 19., 20.],

[np.nan, 22., 23., 24., 25.] ]) #defining the array (the data)

column_avg = np.nanmean(data_set, axis=0) #getting the mean of all columns and ignoring nan

find_nan = np.isnan(data_set) #finding nan in the dataset

data_set[find_nan] =np.take(column_avg, np.where(find_nan)[1]) #replacing each nan with the correct column avg

print (data_set)

[[ 1.          2.         14.66666667  4.          5.        ]
 [ 6.         13.25        8.          9.         10.        ]
 [11.         12.         13.         14.         15.        ]
 [16.         17.         14.66666667 19.         20.        ]
 [ 8.5        22.         23.         24.         25.        ]]


Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.

np.array([

    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
]

In [17]:
dataset = np.array ([
('2024-01-15', 10, 100),
('2024-02-28', 15, 150),
('2024-03-10', 20, 200),
('2024-04-22', 25, 250),
('2024-05-05', 30, 300),
('2024-06-18', 35, 350),
('2024-07-30', 40, 400),
('2024-08-12', 45, 450),
('2024-09-25', 50, 500),
('2024-10-07', 55, 550)] , dtype=object) #defining the data, also adding the dtype as strings

months = [row[0][5:7] for row in dataset] #getting the month part alone from the string in the rows
new_dataset = np.column_stack ((dataset, months))
print( "Dataset with month columns: " , new_dataset)

Dataset with month columns:  [['2024-01-15' 10 100 '01']
 ['2024-02-28' 15 150 '02']
 ['2024-03-10' 20 200 '03']
 ['2024-04-22' 25 250 '04']
 ['2024-05-05' 30 300 '05']
 ['2024-06-18' 35 350 '06']
 ['2024-07-30' 40 400 '07']
 ['2024-08-12' 45 450 '08']
 ['2024-09-25' 50 500 '09']
 ['2024-10-07' 55 550 '10']]
